ARG BUILDPLATFORM
FROM --platform=$BUILDPLATFORM debian:trixie AS build_base
ARG TARGETPLATFORM
ARG BUILDPLATFORM
LABEL maintainer="Christopher Clark <c2dalark@users.noreply.github.com>"
WORKDIR /tmp/src

RUN apt-get update && apt-get upgrade -y \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

FROM --platform=$BUILDPLATFORM build_base AS openssl_build
ARG TARGETPLATFORM
ARG BUILDPLATFORM

ENV DEBIAN_FRONTEND=noninteractive \
    VERSION_OPENSSL=openssl-3.5.6 \
    SHA256_OPENSSL=deae7c80cba99c4b4f940ecadb3c3338b13cb77418409238e57d7f31f2a3b736 \
    SOURCE_OPENSSL=https://www.openssl.org/source/ \
    # OpenSSL OMC
    OPGP_OPENSSL_1=EFC0A467D613CB83C7ED6D30D894E2CE8B3D79F5 \
    # Richard Levitte
    OPGP_OPENSSL_2=7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C \
    # Matt Caswell
    OPGP_OPENSSL_3=8657ABB260F056B1E5190839D9C4D26D0E604491 \
    # Paul Dale
    OPGP_OPENSSL_4=B7C1C14360F353A36862E4D5231C84CDDCC69C45 \
    # Tomas Mraz
    OPGP_OPENSSL_5=A21FAB74B0088AA361152586B8EF1A6BA9DA2D5C \
    # Tim Hudson
    OPGP_OPENSSL_6=C1F33DD8CE1D4CC613AF14DA9195C48241FBF7DD \
    # Kurt Roeckx
    OPGP_OPENSSL_7=E5E52560DD91C556DDBDA5D02064C53641C25E5D \
    # OpenSSL
    OPGP_OPENSSL_8=BA5473A2B0587B07FB27CF2D216094DFD0CB81EF

RUN set -e -x && \
    build_deps="build-essential ca-certificates curl dirmngr gnupg libidn2-0-dev libssl-dev" && \
    apt-get update && apt-get install -y --no-install-recommends \
      $build_deps && \
    curl -L $SOURCE_OPENSSL$VERSION_OPENSSL.tar.gz -o openssl.tar.gz && \
    echo "${SHA256_OPENSSL} ./openssl.tar.gz" | sha256sum -c - && \
    curl -L $SOURCE_OPENSSL$VERSION_OPENSSL.tar.gz.asc -o openssl.tar.gz.asc && \
    GNUPGHOME="$(mktemp -d)" && \
    export GNUPGHOME && \
    gpg --no-tty --keyserver keyserver.ubuntu.com --recv-keys "$OPGP_OPENSSL_1" "$OPGP_OPENSSL_2" "$OPGP_OPENSSL_3" "$OPGP_OPENSSL_4" "$OPGP_OPENSSL_5" "$OPGP_OPENSSL_6" "$OPGP_OPENSSL_7" "$OPGP_OPENSSL_8" && \
    gpg --batch --verify openssl.tar.gz.asc openssl.tar.gz && \
    tar xzf openssl.tar.gz && \
    cd $VERSION_OPENSSL && \
    ./config \
      --prefix=/opt/openssl \
      --openssldir=/opt/openssl \
      no-weak-ssl-ciphers \
      no-ssl3 \
      no-shared \
      enable-ec_nistp_64_gcc_128 \
      -DOPENSSL_NO_HEARTBEATS \
      -fstack-protector-strong && \
    make depend && \
    nproc | xargs -I % make -j% && \
    make install_sw && \
    apt-get purge -y --auto-remove \
      $build_deps && \
    rm -rf \
        /tmp/* \
        /var/tmp/* \
        /var/lib/apt/lists/* && \
    apt-get clean

FROM --platform=$BUILDPLATFORM build_base AS unbound_build
ARG TARGETPLATFORM
ARG BUILDPLATFORM

ENV DEBIAN_FRONTEND=noninteractive \
    NAME=unbound \
    UNBOUND_VERSION=1.25.1 \
    UNBOUND_SHA256=0fe8b6277b0959cfd17562debac0aa5f71e0b02dc4ffa9c60271c583edab586f \
    UNBOUND_DOWNLOAD_URL=https://nlnetlabs.nl/downloads/unbound/unbound-1.25.1.tar.gz

COPY --from=openssl_build /opt/openssl /opt/openssl

COPY ./files/test.sh .
RUN ./test.sh
COPY ./files/build_unbound.sh .
RUN ./build_unbound.sh
RUN rm -rf \
        /opt/unbound/share/man \
        /tmp/* \
        /var/tmp/* \
        /var/lib/apt/lists/* && \
    apt-get clean


FROM debian:trixie AS unbound
ARG NAME=unbound
ARG TARGETPLATFORM
ENV NAME="${NAME}" \
    UNBOUND_VERSION=1.25.1 \
    SUMMARY="${NAME} is a validating, recursive, and caching DNS resolver." \
    DESCRIPTION="${NAME} is a validating, recursive, and caching DNS resolver."

COPY --from=unbound_build /opt /opt

COPY ./files/install_dependencies.sh .
RUN ./install_dependencies.sh
RUN uname -m
RUN rm -rf \
        /opt/unbound/share/man \
        /tmp/* \
        /var/tmp/* \
        /var/lib/apt/lists/* && \
    apt-get clean

COPY data/ /

RUN chmod +x /unbound.sh

WORKDIR /opt/unbound/

ENV PATH=/opt/unbound/sbin:"$PATH"

ARG IMAGE_DESCRIPTION="unbound - a validating, recursive, and caching DNS resolver" \
    IMAGE_URL=c2dalark/unbound \
    IMAGE_REPO=https://github.com/c2dalark/unbound-docker \
    IMAGE_AUTHOR="Christopher Clark <c2dalark@users.noreply.github.com>"

LABEL maintainer=${IMAGE_AUTHOR} \
      org.opencontainers.image.authors=${IMAGE_AUTHOR} \
      org.opencontainers.image.url=${IMAGE_REPO} \
      org.opencontainers.image.documentation=${IMAGE_REPO} \
      org.opencontainers.image.source=${IMAGE_REPO} \
      org.opencontainers.image.version=${UNBOUND_VERSION} \
      org.opencontainers.image.revision=${UNBOUND_VERSION} \
      org.opencontainers.image.vendor=${IMAGE_AUTHOR} \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.ref.name=${UNBOUND_VERSION} \
      org.opencontainers.image.title=${IMAGE_URL} \
      org.opencontainers.image.description=${IMAGE_DESCRIPTION}

EXPOSE 53/tcp
EXPOSE 53/udp

HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD drill @127.0.0.1 cloudflare.com || exit 1

CMD ["/unbound.sh"]