name: multi-arch-testing

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
#  schedule:
#    - cron: '26 16 * * *'
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE: c2dalark/unbound
  CACHE_REPO: c2dalark/unbound-buildcache
  IMAGE-HYPHEN: c2dalark-unbound
  LATEST: 1.25.1
  BUILD_OS: "[ubuntu-latest,ubuntu-24.04-arm]"
  UNBOUND_BUILD: "[1.25.1,1.25.0,1.24.2,1.24.1,1.24.0,1.23.1,1.23.0,1.22.0,1.21.1,1.21.0,1.20.0,1.19.3,1.19.2,1.19.1,1.19.0]"
  TESTING_TAG: "testing"
  TARGET_OS: "[linux]"
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7 #,linux/arm/v5,linux/i386
  ARM_PLATFORMS: linux/arm64,linux/arm/v7 #,linux/arm/v5

jobs:
  pre-build:
    strategy:
      matrix:
        build_os: [ubuntu-latest,ubuntu-24.04-arm]
        unbound_build: [1.25.1] #,1.25.0,1.24.2,1.24.1,1.24.0,1.23.1,1.23.0,1.22.0,1.21.1,1.21.0,1.20.0,1.19.3,1.19.2,1.19.1,1.19.0]
        arch: [amd64,arm64,arm/v7]
        arch-hyphen: [amd64,arm64,armv7]
        target_os: [linux]
        exclude:
          - build_os: ubuntu-latest
            arch: arm64
          - build_os: ubuntu-latest
            arch: arm/v7
          - build_os: ubuntu-24.04-arm
            arch: amd64
          - arch: arm64
            arch-hyphen: armv7
          - arch: arm64
            arch-hyphen: amd64
          - arch: arm/v7
            arch-hyphen: arm64
          - arch: arm/v7
            arch-hyphen: amd64
          - arch: amd64
            arch-hyphen: arm64
          - arch: amd64
            arch-hyphen: amdv7
    runs-on: ${{ matrix.build_os }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      # Get the commit timestamp to use for SOURCE_DATE_EPOCH
      # to create reporoducible images
      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      # Setup QEMU for multi-platform builds
      # https://github.com/docker/setup-qemu-action/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 #v4.2.0

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 #v6.2.0
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=raw,${{ env.TESTING_TAG }}
            type=raw,value=latest,enable=false

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: pre-build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./${{ matrix.unbound_build }}/
          file: ./${{ matrix.unbound_build }}/Dockerfile.temp
          load: true
          outputs: type=docker,name=${{ env.IMAGE }},dest=${{ runner.temp }}/${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }}.tar
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.target_os }}/${{ matrix.arch }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}
            type=gha
          cache-to: |
            type=inline
            type=gha,mode=max
            type=local,dest=${{ runner.temp }}/build-cache/${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }},mode=max
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      - name: Upload image artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: ${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }}.tar
          path: ${{ runner.temp }}/${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}-${{ matrix.target_os }}-${{ matrix.arch-hyphen }}.tar

      - name: Upload build-cache artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: ${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}-${{ matrix.arch-hyphen }}-buildcache
          path: ${{ runner.temp }}/build-cache/*

  build-package-push:
    runs-on: ubuntu-latest
    needs:
    - pre-build
    strategy:
      matrix:
        unbound_build: [1.25.1] #,1.25.0,1.24.2,1.24.1,1.24.0,1.23.1,1.23.0,1.22.0,1.21.1,1.21.0,1.20.0,1.19.3,1.19.2,1.19.1,1.19.0]
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Download build-cache artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          pattern: ${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}*buildcache*
          path: ${{ runner.temp }}/build-cache/

      - name: Download image artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          pattern: ${{ env.IMAGE-HYPHEN }}-${{ matrix.unbound_build }}-linux-*tar*
          path: ${{ runner.temp }}

      - name: Load images arm/v7
        run: find ${{ runner.temp }} -iname c2dalark-unbound*tar -exec docker load --input {} --platform=linux/arm/v7 \;

      - name: Load images arm/64
        run: find ${{ runner.temp }} -iname c2dalark-unbound*tar -exec docker load --input {} --platform=linux/arm64 \;

      - name: Load images amd64
        run: find ${{ runner.temp }} -iname c2dalark-unbound*tar -exec docker load --input {} --platform=linux/amd64 \;

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      # Setup QEMU for multi-platform builds
      # https://github.com/docker/setup-qemu-action/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 #v4.2.0

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 #v4.1.2

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get the commit timestamp to use for SOURCE_DATE_EPOCH
      # to create reporoducible images
      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 #v6.2.0
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=raw,${{ env.TESTING_TAG }}
            type=raw,v${{ env.TESTING_TAG }}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./${{ matrix.unbound_build }}/
          file: ./${{ matrix.unbound_build }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: |
            type=gha,mode=max
            type=local,src=${{ runner.temp }}/build-cache/${{ matrix.unbound_build }}-linux-arm64/
            type=local,src=${{ runner.temp }}/build-cache/${{ matrix.unbound_build }}-linux-armv7/
            type=local,src=${{ runner.temp }}/build-cache/${{ matrix.unbound_build }}-linux-amd64/
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}-linux-arm64
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}-linux-armv7
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}-linux-amd64
          cache-to: |
            type=inline
            type=registry,ref=${{ env.REGISTRY }}/${{ env.CACHE_REPO }}:${{ matrix.unbound_build }}
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
