name: new_ci

on:
  schedule:
    - cron: '26 16 * * *'
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        unbound_build: [1.25.1,1.25.0,1.24.2,1.24.1,1.24.0,1.23.1,1.23.0,1.22.0,1.21.1,1.21.0,1.20.0,1.19.3,1.19.2,1.19.1,1.19.0]
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: true
      context: ./${{ matrix.unbound_build }}/
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-scope: c2dalark/unbound
      cache-mode: max
      meta-images: c2dalark/unbound
      meta-tags: |
        type=sha
        type=raw,${{ matrix.unbound_build }}
        type=raw,v${{ matrix.unbound_build }}
        type=raw,value=latest
      set-meta-annotations: true
      set-meta-labels: true
      build-args: |
        SOURCE_DATE_EPOCH: 0
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

